FROM maven:3.6.3-openjdk-8 AS build
COPY ./ /app
WORKDIR /app
RUN mvn --show-version --update-snapshots --batch-mode clean package

FROM adoptopenjdk:8-jre-hotspot

RUN mkdir /app

WORKDIR /app

COPY --from=build ./app/api/target/customers-api-1.0-SNAPSHOT.jar /app

EXPOSE 8080

CMD ["java", "-jar", "customers-api-1.0-SNAPSHOT.jar"]
#ENTRYPOINT ["java", "-jar", "customers-api-1.0-SNAPSHOT.jar"]
#CMD java -jar customers-api-1.0-SNAPSHOT.jar
