apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: kolan51/rso2021-customers:2021-12-21-20-56-12
          name: customers
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgres://tgqwnsud:XoguIq_gIoHdjDMbKZEnuVj4QWJ7bwLg@hansken.db.elephantsql.com/tgqwnsud
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: tgqwnsud
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: XoguIq_gIoHdjDMbKZEnuVj4QWJ7bwLg
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: customers
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: customers