name: build with Maven and package as Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 1
        format: 'YYYY-MM-DD-HH-mm-ss'
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
       username: kolan51
       password: b23e8588-22c4-417d-91a6-a7782048096e
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile_with_maven_build
        push: true
        tags: rso/customers-main:${{ steps.time.outputs.time }}
